name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/flutter_swiper

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view: 
    git:
      url: https://github.com/hetian9288/transformer_page_view.git
      ref: nullsafety

  flutter_page_indicator: 
    git:
      url: https://github.com/hetian9288/flutter_page_indicator.git
      ref: nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
